-- Teacher-shared DPPs in the student DPP list — 2026-08-08
-- Plan: V1/allmd/TEACHER_TEST_AS_DPP_PLAN.md (Phase 0)
--
-- WHAT THIS ADDS
--   • analytics.dpp_plans.origin — 'auto' (generated by the analytics service
--     after a test) or 'teacher' (materialized from a teacher's DPP share).
--     NOT NULL DEFAULT 'auto' backfills every existing row to today's exact
--     behaviour, which is what makes the retention change below safe.
--   • teacher_share_id / teacher_display_name / teacher_logo_url — the link
--     back to assessment.teacher_dpp_shares (by id, NOT an FK: that table
--     lives behind the USER pool, this one behind the OGCODE pool) plus the
--     institute branding the highlighted student card renders.
--   • expires_at — the 30-day lifetime, copied from the share. The student
--     read path filters on this column directly, so a late or failed sweeper
--     cron can never leak an expired DPP into a student's list.
--
-- RETENTION INTERACTION (the reason `origin` exists)
--   pruneDppPlansForUser keeps only the newest DPP_PLAN_RETENTION_LIMIT (30)
--   plans per user. Scoping that prune to `origin = 'auto'` stops it from
--   (a) deleting a teacher's DPP before its 30 days are up and (b) letting
--   teacher DPPs evict the student's auto-generated post-test DPPs from their
--   own window. See src/legacy/analytics-store.ts.
--
-- Lives in the analytics/OGCODE database alongside analytics.dpp_plans.
-- Metadata-only ADD COLUMNs — no table rewrite on PG 11+. Purely additive and
-- idempotent; safe to re-run. Mirrored by the runtime-ensure DDL in
-- src/legacy/analytics-store.ts.

ALTER TABLE analytics.dpp_plans ADD COLUMN IF NOT EXISTS origin TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE analytics.dpp_plans ADD COLUMN IF NOT EXISTS teacher_share_id TEXT;
ALTER TABLE analytics.dpp_plans ADD COLUMN IF NOT EXISTS teacher_display_name TEXT;
ALTER TABLE analytics.dpp_plans ADD COLUMN IF NOT EXISTS teacher_logo_url TEXT;
ALTER TABLE analytics.dpp_plans ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

-- Student list read: "my non-expired teacher DPPs" and the retention prune's
-- "my auto DPPs, newest first" both hit this.
CREATE INDEX IF NOT EXISTS idx_analytics_dpp_plans_origin
  ON analytics.dpp_plans (user_id, origin, completed, created_at DESC);
-- Sweeper: resolve every materialized plan for a set of expired share ids.
CREATE INDEX IF NOT EXISTS idx_analytics_dpp_plans_teacher_share
  ON analytics.dpp_plans (teacher_share_id) WHERE teacher_share_id IS NOT NULL;
